/*******************************************************************************
 * Copyright (c) 2014 Serdar Ormanlı.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * 
 * Contributors:
 *     Serdar Ormanlı - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 09:03:00 PM EET 
//

package com.sql2nosql.util.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dbname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "host", "port", "dbname" })
@XmlRootElement(name = "settings")
public class Settings {

	protected String host;
	protected Integer port;
	protected String dbname;

	/**
	 * Gets the value of the host property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHost() {
		return host;
	}

	/**
	 * Sets the value of the host property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHost(String value) {
		this.host = value;
	}

	/**
	 * Gets the value of the port property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * Sets the value of the port property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setPort(Integer value) {
		this.port = value;
	}

	/**
	 * Gets the value of the dbname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDbname() {
		return dbname;
	}

	/**
	 * Sets the value of the dbname property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDbname(String value) {
		this.dbname = value;
	}

}
